### PR TITLE
Ledger path support

### PR DESCRIPTION
**Pull request by stupid-boar**
master branch use only first account (path ignored)

Expected:
```ts
  namedAccounts: {
    deployer: {
      default: 0,
      5: "ledger://m/44'/60'/0'/0/0",
    },
  },
```

### CODE REVIEW

**Comment by stupid-boar** [comment]
@wighawag 
I made it work)
I change the address to 0x0000...0 on config parsing
```ts
if (protocolSplit[0].toLowerCase() === 'ledger') {
    address = '0x0000000000000000000000000000000000000000';
    addressesToProtocol[address.toLowerCase()] = spec;
```
When (transport init) I take PATH from protocol string (this is true, because hardware level)
```ts
ethersSigner = ledgerSignerFactory(
  provider,
  registeredProtocol.substr(9)
);
```

We have successfully deployed [smart contract](https://goerli.etherscan.io/address/0x20208e70946a983eae79ae62e5658189a9f37650)

**Comment by wighawag** [comment]
The issue is that namedAccounts are also used to references address, if you set it to zero address for all ledger then you cannot use that functionality

**Comment by stupid-boar** [comment]
I'll fix it soon
`ledger://m/44'/60'/0'/0/0:<address>`

**Comment by stupid-boar** [comment]
@wighawag fixed)

**Comment by wighawag** [comment]
Nice!
should have mentioned before, but we need to provide backward compatibility for those we put `ledger://<address>`
in this case, the default path should be taken like before

**Comment by stupid-boar** [comment]
I'll fix it soon

**Comment by stupid-boar** [comment]
@wighawag done)

**Comment by stupid-boar** [comment]
@wighawag it's done)

**Comment by stupid-boar** [comment]
@wighawag i fixed concurrent access to ledger device by using singleton pattern. Now it's work!)

**Pull request closed without merging**
