### PR TITLE
feat: add an inital snapshot to revert to

### PR DESCRIPTION
**Pull request by adjisb**

### CODE REVIEW

**Comment by wighawag** [comment]
It is already implemented below with the option --deploy-fixture (also settable via env: HARDHAT_DEPLOY_FIXTURE)

**Comment by adjisb** [comment]
I may be wrong, but I thing that this fixture is empty (without any contracts) and the other one is after all the migrations.
I want a way to revert to a clean state when I'm testing.

**Comment by wighawag** [comment]
you mean, your revert to a clean state , without any contract ?
you can get that by not using `--deploy-fixture` and use a normal snapshot in your test.

**Comment by adjisb** [comment]
The problem I have is that when is the turn of my test to run I don't know what's the state of the evm. The state seems to depend on the previous tests and the order in which the were executed, and the migration scripts and their dependencies (if fixture(['XX'] was called). 
There is a way to revert to a clean state before running my test suite ?

**Comment by wighawag** [comment]
hardhat-deploy has the concept of deployment fixture, that let you to revert to a specific state of deployment based on tags.  It should not depend on previous tests unless you do something peculiar with it. I need more info
hardhat-deploy also come with the posibility to create fixture via `deployments.createFixture()` 
you could use the latter I guess, but I could definitely add an function that reset all like to make it easy.
The PR as it stand though is basically the same as `--deploy-fixture` and is not always desriable
Need to review the system more. I ll leave it open for now.
If you have an example repo exemplifying your issue, it would help.

**Comment by adjisb** [comment]
https://github.com/adjisb/hardhat-deploy-test/tree/93339997d1713c8dc46fc34e11e9e2f5603d02f3

**Comment by wighawag** [comment]
I see, the current behavior is expected actually. if you want a clean env you ll need to reset to the snapshot created by `deployments.fixture`. In your test you called it and this generated tx. The only way to reset is to call `evm_revert`
Else the blockchain will continue with that state and hardhat-deploy simply keep in memory the contract deployed on that state.

Note though, as you figured out,  there must be an initial snapshot to revert to. else `evm_revert` cannot do anything. But even this will not be enough as you need to tell hardhat-deploy to then clean up its memory about deployed contract

I agree that hardhat-deploy should come with this function. I think we could have a snapshot created by `evm_snapshot` before anything happen and save the empty deployment set for it. Maybe I could call it `deployments.emptyFixture()` or something

By the way, for the second test, not sure what you expect but since the contract code is not updated, it will keep reusing the previously deployed contract like in behave in deploy scripts,

**Comment by wighawag** [comment]
By the way what is the intention behind the test that expect `getContract("ContractName")` Seems like you are testing hardhat-deploy

Also what would be the intention behind the test that try to deploy a new instance.

Just want to know the use case for resesting to an empty snapshot. After all hardhat-deploy `deployments.fixture` is to test contract deployed through its deploy script system so that you test exactly what these deployment will do on mainnet.

if you want to test these contract in different deployment configuration, you probably want to deploy them with different config and name

But I am curious and open to add an option if that make your life easier

**Comment by adjisb** [comment]
I want a clean environment to test the contracts. With hardhat-deploy the different tests suites end up getting a mixed unpredictable evm environment. Probably I'm using the wrong tool to snapshot/revert the evm ?
Let say you have a lot of test suits, in some you used fixture(['A']), you deploy some mocks, etc. In next suite you use fixture(['B']) this fixture end up getting a snapshot that contains fixture(['A']) + mocks + fixture(['B']). So the result depends on the execution order, if fixture(['A']) and fixture(['B']) share some contracts I will end up having a strange mix, etc.
My plan was to clean the environment reverting to the initial clean snapshot on each suite, then use createFixture and inside it fixture([...]).

**Comment by wighawag** [comment]
> I want a clean environment to test the contracts. With hardhat-deploy the different tests suites end up getting a mixed unpredictable evm environment.

As I said, in your test you showed me, you did nothing to revert back, so ultimately hardhat-deploy did the right thing, keep track of the current state.

> Let say you have a lot of test suits, in some you used fixture(['A']), you deploy some mocks, etc. In next suite you use fixture(['B']) this fixture end up getting a snapshot that contains fixture(['A']) + mocks + fixture(['B']). So the result depends on the execution order, if fixture(['A']) and fixture(['B']) share some contracts I will end up having a strange mix, etc.

That's not true, hardhat-deploy handle that case and was made for it.
if you do
- deployments.fixture(["A"])
and then
- deployments.fixture(["B"])

then an evm_revert would have happen and both test would have no state in common




My plan was to clean the environment reverting to the initial clean snapshot on each suite, then use createFixture and inside it fixture([...]).

**Comment by wighawag** [comment]
If you want a mixture of fixture A and B you use `deployments.fixture(["A", "B"])` both tags will be used, and this will be  a different snapshot than `deployments.fixture(["A"])` or `deployments.fixture(["B"])`

Then if you need to deploy mock on top, you use `deployments.createFixture` which can contains call to `deployments.fixture`

see for example :https://github.com/wighawag/template-ethereum-contracts/blob/main/test/GreetingsRegistry.test.ts

**Comment by adjisb** [comment]
> > Let say you have a lot of test suits, in some you used fixture(['A']), you deploy some mocks, etc. In next suite you use fixture(['B']) this fixture end up getting a snapshot that contains fixture(['A']) + mocks + fixture(['B']). So the result depends on the execution order, if fixture(['A']) and fixture(['B']) share some contracts I will end up having a strange mix, etc.
> 
> That's not true, hardhat-deploy handle that case and was made for it.
> if you do
> 
> * deployments.fixture(["A"])
>   and then
> * deployments.fixture(["B"])
> 
> then an evm_revert would have happen and both test would have no state in common
I disagree,  deployments.fixture(["B"]) will get everything that happens after  deployments.fixture(["A"]), less balance in the account any deployment, whatever.

Anyway I'm closing this one because I decided to use hardhat_reset that is a better option for my use case.

**Pull request closed without merging**
