### PR TITLE
Ledger path support

### PR DESCRIPTION
**Pull request by stupid-boar**
master branch use only first account (path ignored)

Expected:
```ts
  namedAccounts: {
    deployer: {
      default: 0,
      11155111: "ledger://m/44'/60'/20'/0/0:0x9bA15E762398456ce03eAA382253b56Ed5dA882a",
    },
  },
```

### CODE REVIEW

**Comment by stupid-boar** [comment]
@wighawag pls)

**Comment by sshmaxime** [comment]
This is really nice ! Thanks @stupid-boar, i hope this gets merged soon

**Comment by wighawag** [comment]
Thanks @stupid-boar  !
it is now published on 0.11.27

**Comment by stupid-boar** [comment]
@wighawag thx you very much! we love your project

**Pull request merged**
