### PR TITLE
Fix missing metadata when using fullyQualifiedName

### LINKED ISSUE #137: Bug: Metadata missing in deployment for fully qualified path to artifact
Metadata is not read into deployment file for fully qualified artifact:

```
await deployments.deploy('ServiceReceiver', {
    contract: 'contracts/INFI/ServiceReceiver.sol:ServiceReceiver', // bug
    from: deployerAddress, // Deployer will be performing the deployment transaction.
    args, // Arguments to the contract's constructor.
    log: true, // Display the address and gas used in the console (not when run in test though).
  });
```

### PR DESCRIPTION
**Pull request by heri16**
Fixes #137 .

### CODE REVIEW

**Comment by heri16** [comment]
@wighawag could you take a look?

**Comment by wighawag** [comment]
I am currently away, not sure yet when I ll be able to review it

**Comment by wighawag** [comment]
Looks good, thanks @heri16 !

**Comment by wighawag** [comment]
available in 0.8.11

**Pull request merged**
