### PR TITLE
Allow to define custom deterministic deployment information

### PR DESCRIPTION
**Pull request by rmeissner**
Currently the proxy/ factory used for the deterministic deployment is hardcoded to https://github.com/Arachnid/deterministic-deployment-proxy This library uses a presigned transaction that doesn't use any replay protection (EIP-155). Some chains (e.g. Celo or Avalanche) enforce the use of replay protection and therefore it is not possible to use the current deterministic deployment there. 

This PR add the possibility to define per network information for the deterministic deployment. Alternatively a function can be used to be more flexible.

An example of this can be seen in the https://github.com/gnosis/safe-contracts:

We define a env var to enable the custom deterministic deployment:
https://github.com/gnosis/safe-contracts/blob/3922fa23e85adda6cab9cb574c3157d3bbdb0cde/hardhat.config.ts#L48-L58

and then apply it to the config
https://github.com/gnosis/safe-contracts/blob/3922fa23e85adda6cab9cb574c3157d3bbdb0cde/hardhat.config.ts#L109

Note: This is a draft as the docs have not been adjusted. Before doing this I wanted to check if this would be worth being included in the library.

### CODE REVIEW

**Comment by wighawag** [comment]
Hey @rmeissner thanks for the PR, I did not have time yet to fully review it, but looks good.
I ll see if I can fond some time this week to look closer

**Comment by rmeissner** [comment]
Cool, let me know if any changes are required :)

**Comment by wighawag** [comment]
Looks good.
Like you mention, if you could add documentation that would be superb
Thanks

**Comment by rmeissner** [comment]
I added some documentation. Is this sufficient or do you have some open questions that I should answer with it?

**Comment by wighawag** [comment]
Perfect, thanks!

**Comment by rmeissner** [comment]
Thank you for merging :)

Just for an internal information loop, when is it expected to have this available in a release on npm?

**Comment by wighawag** [comment]
most likely this week

**Comment by wighawag** [comment]
0.9.2 released, thanks again for the PR!

**Pull request merged**
