### PR TITLE
Adapt to new buidler version

### PR DESCRIPTION
**Pull request by fvictorio**
Hi @wighawag! This is some initial work towards adapting `buidler-deploy` to buidler's next major version.

There are some things here that might change, like how `Artifacts` is used. Also, I commented some lines that enabled logging in the node because those crash with the new version. I'm not sure how to fix that.

### CODE REVIEW

**Comment by wighawag** [comment]
Hi @fvictorio thanks for looking into that!
I ll have a closer look and merge it.

Re  node and logging, as mentioned to Pato, there is these 2 issues that would allow me to solve it : 
https://github.com/nomiclabs/buidler/issues/730
https://github.com/nomiclabs/buidler/issues/729

**Comment by wighawag** [comment]
Actually @fvictorio do you know what changed so that I cannot access provider._ethModule ?
is that a typescript compiler setting that make private var truly private ?
I cannot see the changes that would make it impossible to access private variable

**Comment by fvictorio** [comment]
I think it's not that it isn't accessible, but that the module is not created yet. The initialization is done after the first method is sent.

It was working before because *I think* it was behind a proxy, or something like that. @alcuadrado can explain it better.

Now that I write this, I'm thinking that maybe the easiest (but not proper) solution is to just call `init` before those lines. It's a temporary solution, but it might work?

**Comment by wighawag** [comment]
Ok, but since I call await runDeploy before and in my test I have deployment, the _init should have been called already

Also I just tried to call _init but it fails with `TypeError: provider._init is not a function`
```
const provider = bre.network.provider as any;
await provider._init();
provider._loggingEnabled = true;
if (provider._ethModule) {
  provider._ethModule._logger = provider._logger;
}
```

I am probably missing something but cannot figure what it is :)

**Comment by fvictorio** [comment]
Oh, yes, that's because now there's a backward compatibility and wrapping mechanism that makes this tricky.

I added a very hackish and temporary solution. That should work for now, but we should add a proper API for this.

**Comment by wighawag** [comment]
Cool, thanks!
yes agreed, a proper api is the only proper solution. even before it was a hack :)

**Pull request closed without merging**
