### PR TITLE
Add support for optimism goerli etherscan api

### PR DESCRIPTION
**Pull request by leekt**
Added chain id 420 in etherscan.ts, used https://api-goerli-optimism.etherscan.io for api url

### CODE REVIEW

**Comment by wighawag** [comment]
does not look like https://api-goerli-optimism.etherscan.io is working

**Comment by leekt** [comment]
hmmm it worked for me on something like  `npx hardhat etherscan-verify --network optimismGoerli --api-url https://api-goerli-optimism.etherscan.io`

**Comment by leekt** [comment]
and the link itself seems to be working for me
image

**Comment by wighawag** [comment]
you right, thanks @leekt !

**Pull request merged**
